#!/usr/bin/perl -w

use strict;
use warnings;

our $nossaLibDir;

BEGIN{
  use File::Basename qw/dirname/;
  use Cwd qw/realpath/;
  $nossaLibDir = realpath( dirname( __FILE__ ).'/../lib' );
  push( @INC, $nossaLibDir  )
    unless grep { $_ eq $nossaLibDir } @INC;
}

use Net::OpenID::Server::Standalone;

Net::OpenID::Server::Standalone::setup;
