#!/usr/bin/perl -w

use strict;
use warnings;

our $nossaLibDir;

BEGIN{
  use File::Basename qw/dirname/;
  use Cwd qw/realpath/;
  $nossaLibDir = realpath( dirname( __FILE__ ).'/../lib' );
  push( @INC, $nossaLibDir  )
    unless grep { $_ eq $nossaLibDir } @INC;
}

use Net::OpenID::Server::Standalone;

Net::OpenID::Server::Standalone::setup;

exit;

use CGI;
use CGI::Session;
use HTML::Entities qw/encode_entities/;


CGI::Session->name( 'pvo' );
my $session = new CGI::Session( 'driver:DB_File;serializer:FreezeThaw', undef, );

my $cgi = new CGI;
$cgi->charset( 'utf-8' );

my $action = $cgi->param( 'action' );

my $hiddens = &session_cgi_hiddens;


#  use Data::Dumper;
#  print Dumper $cgi;
#  print Dumper $check_cgi;

print $cgi->header;
my $sess_vars = $session->param('vars');
if( $session->param( 'login' ) ){
  if( $action eq 'logout' ){
    $session->delete;
    $session->flush;
    &print_form;
  #  } elsif( $action eq 'login' ){
  #    print $session->header( -status => "301 Logged in successfully", -location => "/id?$check_qs", );
  } elsif(   ( $action eq 'login' )
            and
            ( defined $sess_vars )
            and
            ( defined $sess_vars->{ 'openid.trust_root' } )
           ){
    my $trust_root = $sess_vars->{ 'openid.trust_root' };
    &print_trust_form( encode_entities( $trust_root ) );
  } else {
    &print_logout_form;
  }
} else {
  &print_form;
}

sub print_form {
  $hiddens = &session_cgi_hiddens;
  print <<EOF;
<html><form action='/id' method='POST'
>$hiddens<table width='0' cellspacing='0' cellpadding='0' border='0'>
<tr>
<td>Login: </td><td><input type='text' name='login' /></td>
</tr><tr>
<td>Pzzwd: </td><td><input type='password' name='password' /></td>
</tr>
<tr><td colspan='2' align='center'><input type='submit' name='button' value='Go' /></td></tr>
</table></form></html>
EOF
}
sub print_logout_form {
  print <<EOF;
<html><form action='$ENV{ SCRIPT_NAME }' method='POST'
>$hiddens<input type='hidden' name='action' value='logout'
/><input type='submit' name='button' value='Out' 
/></form></html>
EOF
}
sub print_trust_form {
  my $trust_root_htmled = shift;
  print <<EOF;
<html><form action='/id' method='POST'
>$hiddens<table width='0' cellspacing='0' cellpadding='0' border='0'>
<tr>
<tr><td colspan='2' align='center'>Trust this root?<br /><b>$trust_root_htmled</b></td></tr>
<tr><td align='center'><input type='submit' name='setup_trust_root' value='Yes' /></td><td align='center'><input type='submit' name='setup_trust_root' value='No' /></td>
</tr>
</table></form></html>
EOF
}
sub session_cgi_hiddens {
  my $sess_cgi = $session->param( 'vars' );
  my $sess_cgi_htmled = { map{  
      encode_entities( $_, '<>&"\'' ) => encode_entities( $sess_cgi->{ $_ }, '<>&"\'' )
  } keys %$sess_cgi };
  return join "\n",
    map {
      my $val = $sess_cgi_htmled->{ $_ };
      "<input type='hidden' name='$_' value='$val' />";
    } keys  %$sess_cgi_htmled  ;
}
